# Generated by Django 6.0.3 on 2026-04-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='facility_type',
            field=models.CharField(choices=[('academic', 'Academic Building'), ('administrative', 'Administrative'), ('library', 'Library'), ('sports', 'Sports & Recreation'), ('dining', 'Dining'), ('service', 'Service Facility')], default='academic', max_length=20),
        ),
    ]
