# Generated by Django 6.0.3 on 2026-04-01 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminauditlog',
            old_name='user_agent',
            new_name='new_value_json',
        ),
        migrations.RemoveField(
            model_name='adminauditlog',
            name='new_values',
        ),
        migrations.RemoveField(
            model_name='adminauditlog',
            name='old_values',
        ),
        migrations.RemoveField(
            model_name='adminauditlog',
            name='user',
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='entity_label',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='old_value_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminauditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('soft_delete', 'Soft Delete'), ('restore', 'Restore'), ('approve', 'Approve'), ('reject', 'Reject'), ('publish', 'Publish'), ('reset_password', 'Reset Password')], max_length=20),
        ),
        migrations.AlterField(
            model_name='adminauditlog',
            name='entity_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adminauditlog',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
