# Generated by Django 6.0.3 on 2026-04-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_user_agent_adminauditlog_new_value_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectivitylog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='devicepreference',
            name='user',
        ),
        migrations.RemoveField(
            model_name='feedbackflag',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='feedbackflag',
            name='resolved_by',
        ),
        migrations.RemoveField(
            model_name='feedbackflag',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='room',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usageanalytics',
            name='user',
        ),
        migrations.DeleteModel(
            name='AppUsage',
        ),
        migrations.DeleteModel(
            name='ConnectivityLog',
        ),
        migrations.DeleteModel(
            name='DevicePreference',
        ),
        migrations.DeleteModel(
            name='FeedbackFlag',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='UsageAnalytics',
        ),
    ]
