# Generated by Django 6.0.3 on 2026-04-01 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('source_label', models.CharField(help_text='Department label shown on the mobile notification card', max_length=200)),
                ('source_color', models.CharField(default='orange', help_text='Color key for the department chip on mobile', max_length=20)),
                ('scope', models.CharField(choices=[('campus_wide', 'Entire Campus (all users)'), ('all_college', 'All College Students'), ('basic_ed_only', 'Basic Education Only'), ('department', 'Specific Department Only')], default='campus_wide', max_length=20)),
                ('target_department', models.CharField(blank=True, help_text='Set when scope=department to filter which users see this', max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='pending_approval', max_length=20)),
                ('requires_approval', models.BooleanField(default=True)),
                ('rejection_note', models.TextField(blank=True, help_text='Reason for rejection — shown to the submitting admin', null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_announcements', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
