# Generated by Django 6.0.3 on 2026-04-01 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '__first__'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='action_url',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='data_json',
        ),
        migrations.AddField(
            model_name='notification',
            name='announcement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='announcements.announcement'),
        ),
        migrations.AddField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='source_color',
            field=models.CharField(default='orange', help_text='Color key: red, dark_blue, green, charcoal, purple, teal, amber, blue, dark_green, indigo, brown, orange', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='source_label',
            field=models.CharField(blank=True, default='', help_text='Department or office name shown on the mobile card', max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Important'), (3, 'Urgent'), (4, 'Emergency')], default=1),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('announcement', 'Department Announcement'), ('info', 'General Info'), ('emergency', 'Emergency'), ('facility_update', 'Facility Update'), ('room_update', 'Room/Classroom Update'), ('system_maintenance', 'System Maintenance'), ('app_update', 'App Update')], default='info', max_length=30),
        ),
    ]
