# Generated by Django 6.0.3 on 2026-04-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationnode',
            name='map_svg_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
