# Generated by Django 6.0.3 on 2026-04-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='user_type',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='department_label',
            field=models.CharField(blank=True, help_text='Override label shown on announcements. Auto-filled from department if blank.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='display_name',
            field=models.CharField(blank=True, help_text='Full name or title shown in audit logs and admin panel', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Safety and Security Office'), ('dean', 'College Dean'), ('program_head', 'College Program Head'), ('basic_ed_head', 'Basic Education Head')], default='program_head', max_length=20),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='department',
            field=models.CharField(blank=True, choices=[('safety_security', 'Safety and Security Office'), ('office_of_the_dean', 'Office of the Dean'), ('college_agriculture', 'College of Agriculture and Fisheries'), ('college_criminology', 'College of Criminal Justice Education'), ('college_business', 'College of Business and Good Governance'), ('college_ict', 'College of Information and Communication Technology'), ('dept_civil_engineering', 'Department of Civil Engineering'), ('college_teacher_education', 'College of Teacher Education'), ('tesda', 'Technical Education and Skills Development Authority (TESDA)'), ('general_education', 'General Education Department'), ('basic_education', 'Basic Education Department')], max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='adminuser',
            table='admin_users',
        ),
    ]
