# Generated by Django 6.0.3 on 2026-04-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_adminuser_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='office_location',
            field=models.CharField(blank=True, help_text='Office location for public directory', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='show_email_public',
            field=models.BooleanField(default=False, help_text='Allow email to be shown in public directory'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'System Administrator'), ('dean', 'College Dean'), ('program_head', 'College Program Head'), ('basic_ed_head', 'Basic Education Head')], default='program_head', max_length=20),
        ),
    ]
